steps:
  # Build da imagem Docker
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/emendas-automation:$BUILD_ID",
        "-t",
        "gcr.io/$PROJECT_ID/emendas-automation:latest",
        ".",
      ]

  # Push da imagem para Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/emendas-automation:latest"]

  # Deploy no Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "emendas-automation",
        "--image",
        "gcr.io/$PROJECT_ID/emendas-automation:latest",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "2Gi",
        "--cpu",
        "1",
        "--timeout",
        "900",
        "--max-instances",
        "1",
        "--set-env-vars",
        "GOOGLE_SHEET_ID=${_GOOGLE_SHEET_ID}",
        "--service-account",
        "${_SERVICE_ACCOUNT_EMAIL}",
      ]

# Variáveis substituíveis
substitutions:
  _GOOGLE_SHEET_ID: "" # Será definido no comando de build
  _SERVICE_ACCOUNT_EMAIL: "" # Será definido no comando de build

options:
  logging: CLOUD_LOGGING_ONLY
